"use client";
import type { VCMemoData } from "@/lib/types";

const REC_META = {
  PASS:   { label: "PASS",   bg: "bg-red-50",    border: "border-red-300",   badge: "bg-red-600 text-white",   text: "text-red-700"  },
  WATCH:  { label: "WATCH",  bg: "bg-amber-50",  border: "border-amber-300", badge: "bg-amber-500 text-white", text: "text-amber-700"},
  INVEST: { label: "INVEST", bg: "bg-green-50",  border: "border-green-300", badge: "bg-green-600 text-white", text: "text-green-700"},
};

interface Props { memo: VCMemoData }

export function VCMemo({ memo }: Props) {
  const meta = REC_META[memo.recommendation] ?? REC_META.WATCH;

  return (
    <div className={`rounded-2xl border-2 ${meta.border} ${meta.bg} p-6`}>
      {/* Header */}
      <div className="flex items-start justify-between gap-4 mb-5">
        <div className="flex-1 min-w-0">
          <div className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-1">
            Internal Investment Committee Memo · Confidential
          </div>
          <p className={`text-base font-semibold leading-snug ${meta.text}`}>
            {memo.headline}
          </p>
        </div>
        <span className={`inline-flex items-center rounded-xl px-3 py-1.5 text-sm font-black tracking-wide flex-shrink-0 ${meta.badge}`}>
          {meta.label}
        </span>
      </div>

      {/* Memo body */}
      <div className="rounded-xl bg-white/70 border border-black/5 p-4 mb-4">
        <div className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-2">Memo</div>
        <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">
          {memo.memo}
        </p>
      </div>

      {/* Two-column: red flags + what would change our mind */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {memo.red_flags.length > 0 && (
          <div className="rounded-xl bg-red-100/50 border border-red-200 p-4">
            <div className="text-[10px] font-bold uppercase tracking-widest text-red-500 mb-3">Red Flags</div>
            <ul className="space-y-2">
              {memo.red_flags.map((flag, i) => (
                <li key={i} className="flex gap-2 text-xs text-gray-700 leading-snug">
                  <span className="text-red-500 flex-shrink-0 mt-0.5">▸</span>
                  {flag}
                </li>
              ))}
            </ul>
          </div>
        )}
        {memo.what_would_change_our_mind.length > 0 && (
          <div className="rounded-xl bg-green-100/50 border border-green-200 p-4">
            <div className="text-[10px] font-bold uppercase tracking-widest text-green-600 mb-3">What Would Change Our Mind</div>
            <ul className="space-y-2">
              {memo.what_would_change_our_mind.map((cond, i) => (
                <li key={i} className="flex gap-2 text-xs text-gray-700 leading-snug">
                  <span className="text-green-500 flex-shrink-0 mt-0.5">▸</span>
                  {cond}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <div className="mt-4 text-[10px] text-gray-400 text-right">
        Generated by AI CFO Agent · Claude Haiku · For illustrative purposes only
      </div>
    </div>
  );
}
