#!/usr/bin/env python3
"""
send_morning_briefings.py — Morning CFO Briefing delivery script.

Run via cron at 7 AM daily:
  0 7 * * * /path/to/venv/bin/python3 scripts/send_morning_briefings.py

Or manually for a single run:
  python3 scripts/send_morning_briefings.py --run-id <uuid> --email you@startup.com

Requirements (pip install):
  httpx sendgrid twilio slack-sdk

Environment variables:
  DATABASE_URL            SQLite or PostgreSQL connection string
  ANTHROPIC_API_KEY       Claude Haiku for action items
  SENDGRID_API_KEY        For email delivery (optional)
  TWILIO_ACCOUNT_SID      For SMS delivery (optional)
  TWILIO_AUTH_TOKEN       For SMS delivery (optional)
  TWILIO_FROM_NUMBER      E.164 format, e.g. +15005550006
  SLACK_WEBHOOK_URL       Single webhook for testing (optional)
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys
import uuid
from pathlib import Path

# Ensure project root is on the path
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv()

import httpx


API_BASE = os.getenv("MORNING_BRIEFING_API", "http://localhost:8000")


# ── Delivery helpers ──────────────────────────────────────────────────────────

def _format_sms(d: dict) -> str:
    """Format briefing as SMS (≤320 chars for readability)."""
    lines = [
        f"🏦 AI CFO — {d['company_name']}",
        f"💰 {d['runway_months']:.1f}mo runway | MRR {'+' if d['mrr_change_pct']>0 else ''}{d['mrr_change_pct']:.1f}%",
    ]
    if d["urgent"]:
        lines.append(f"🚨 {d['urgent'][0]}")
    if d["actions"]:
        lines.append(f"▶ {d['actions'][0]}")
    lines.append("Reply FULL for details")
    return "\n".join(lines)


def _format_slack(d: dict) -> dict:
    """Format briefing as Slack Block Kit payload."""
    runway_emoji = "🔴" if d["runway_months"] < 3 else "🟡" if d["runway_months"] < 6 else "🟢"
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": f"🌅 Morning CFO Briefing — {d['company_name']}"}},
        {"type": "section", "fields": [
            {"type": "mrkdwn", "text": f"{runway_emoji} *Runway:* {d['runway_months']:.1f} months"},
            {"type": "mrkdwn", "text": f"🔥 *Burn:* ${d['burn_rate']:,}/wk ({'+' if d['burn_change_pct']>0 else ''}{d['burn_change_pct']:.1f}%)"},
            {"type": "mrkdwn", "text": f"📈 *MRR:* ${d['mrr']:,}/wk ({'+' if d['mrr_change_pct']>0 else ''}{d['mrr_change_pct']:.1f}%)"},
            {"type": "mrkdwn", "text": f"📊 *Gross Margin:* {d['gross_margin_pct']:.0f}%"},
        ]},
    ]
    if d["urgent"]:
        urgent_text = "\n".join(f"• {u}" for u in d["urgent"])
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": f"🚨 *Urgent Alerts:*\n{urgent_text}"}})
    if d["good_news"]:
        good_text = "\n".join(f"• {g}" for g in d["good_news"])
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": f"✅ *Good News:*\n{good_text}"}})
    if d["actions"]:
        action_text = "\n".join(f"{i+1}. {a}" for i, a in enumerate(d["actions"]))
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": f"📋 *Today's Actions:*\n{action_text}"}})
    blocks.append({"type": "divider"})
    blocks.append({"type": "context", "elements": [
        {"type": "mrkdwn", "text": f"Week of {d['week_start']} · Generated by AI CFO Agent · ~$0.003/call"}
    ]})
    return {"blocks": blocks}


def _format_email_html(d: dict) -> str:
    """Format briefing as HTML email."""
    runway_color = "#ef4444" if d["runway_months"] < 3 else "#f59e0b" if d["runway_months"] < 6 else "#22c55e"
    urgent_html  = "".join(f"<li>{u}</li>" for u in d["urgent"])  if d["urgent"]   else ""
    good_html    = "".join(f"<li>{g}</li>" for g in d["good_news"]) if d["good_news"] else ""
    action_html  = "".join(f"<li>{a}</li>" for a in d["actions"])  if d["actions"]  else ""
    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /><title>Morning CFO Briefing</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f5f5f7;margin:0;padding:32px">
  <div style="max-width:600px;margin:0 auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)">
    <div style="background:linear-gradient(135deg,#f59e0b,#ea580c);padding:24px 32px">
      <div style="color:white;font-size:22px;font-weight:900">🌅 Morning CFO Briefing</div>
      <div style="color:rgba(255,255,255,0.85);font-size:13px;margin-top:4px">{d['company_name']}</div>
    </div>
    <div style="padding:24px 32px">
      <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
        <tr>
          <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center">
            <div style="font-size:28px;font-weight:900;color:{runway_color}">{d['runway_months']:.1f}</div>
            <div style="font-size:11px;color:#6b7280;margin-top:2px">months runway</div>
          </td>
          <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center;margin-left:8px">
            <div style="font-size:18px;font-weight:700;color:#111">${d['burn_rate']:,}</div>
            <div style="font-size:11px;color:#6b7280">burn /wk
              <span style="color:{'#ef4444' if d['burn_change_pct']>0 else '#22c55e'}">
                ({'+' if d['burn_change_pct']>0 else ''}{d['burn_change_pct']:.1f}%)
              </span>
            </div>
          </td>
          <td style="padding:12px;background:#f9fafb;border-radius:8px;text-align:center">
            <div style="font-size:18px;font-weight:700;color:#111">${d['mrr']:,}</div>
            <div style="font-size:11px;color:#6b7280">MRR /wk
              <span style="color:{'#22c55e' if d['mrr_change_pct']>0 else '#ef4444'}">
                ({'+' if d['mrr_change_pct']>0 else ''}{d['mrr_change_pct']:.1f}%)
              </span>
            </div>
          </td>
        </tr>
      </table>
      {'<h3 style="color:#ef4444;font-size:13px;margin:0 0 8px">🚨 Urgent Alerts</h3><ul style="margin:0 0 20px;padding-left:20px;font-size:13px;color:#374151">' + urgent_html + '</ul>' if urgent_html else ''}
      {'<h3 style="color:#16a34a;font-size:13px;margin:0 0 8px">✅ Good News</h3><ul style="margin:0 0 20px;padding-left:20px;font-size:13px;color:#374151">' + good_html + '</ul>' if good_html else ''}
      {'<h3 style="color:#2563eb;font-size:13px;margin:0 0 8px">📋 Today\'s Actions</h3><ol style="margin:0 0 20px;padding-left:20px;font-size:13px;color:#374151">' + action_html + '</ol>' if action_html else ''}
      <div style="font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:16px;margin-top:8px">
        Week of {d['week_start']} · AI CFO Agent · ~$0.003/briefing
      </div>
    </div>
  </div>
</body>
</html>"""


async def _send_email(to: str, subject: str, html: str) -> None:
    api_key = os.getenv("SENDGRID_API_KEY")
    if not api_key:
        print(f"  ⚠  SENDGRID_API_KEY not set — skipping email to {to}")
        return
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            "https://api.sendgrid.com/v3/mail/send",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "personalizations": [{"to": [{"email": to}]}],
                "from": {"email": os.getenv("SENDGRID_FROM", "cfo@ai-cfo.app"), "name": "AI CFO"},
                "subject": subject,
                "content": [{"type": "text/html", "value": html}],
            },
            timeout=15,
        )
    if resp.status_code not in (200, 202):
        print(f"  ✗  SendGrid error {resp.status_code}: {resp.text[:120]}")
    else:
        print(f"  ✓  Email sent to {to}")


async def _send_slack(webhook_url: str, payload: dict) -> None:
    async with httpx.AsyncClient() as client:
        resp = await client.post(webhook_url, json=payload, timeout=10)
    if resp.status_code != 200:
        print(f"  ✗  Slack error {resp.status_code}: {resp.text[:80]}")
    else:
        print(f"  ✓  Slack message sent")


async def _send_sms(to: str, body: str) -> None:
    sid   = os.getenv("TWILIO_ACCOUNT_SID")
    token = os.getenv("TWILIO_AUTH_TOKEN")
    frm   = os.getenv("TWILIO_FROM_NUMBER")
    if not (sid and token and frm):
        print(f"  ⚠  Twilio credentials not set — skipping SMS to {to}")
        return
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"https://api.twilio.com/2010-04-01/Accounts/{sid}/Messages.json",
            auth=(sid, token),
            data={"From": frm, "To": to, "Body": body},
            timeout=15,
        )
    if resp.status_code not in (200, 201):
        print(f"  ✗  Twilio error {resp.status_code}: {resp.text[:120]}")
    else:
        print(f"  ✓  SMS sent to {to}")


# ── Main logic ────────────────────────────────────────────────────────────────

async def send_briefing(
    run_id: str,
    company_name: str = "Your Company",
    email: str | None = None,
    phone: str | None = None,
    slack_webhook: str | None = None,
) -> None:
    # 1. Fetch briefing from API
    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"{API_BASE}/briefing/preview",
            json={"run_id": run_id, "company_name": company_name},
            timeout=30,
        )
    if resp.status_code != 200:
        print(f"  ✗  API error {resp.status_code}: {resp.text[:120]}")
        return
    d = resp.json()
    print(f"  ✓  Briefing generated for {d['company_name']} | runway={d['runway_months']:.1f}mo")

    # 2. Deliver
    tasks = []
    subject = f"🌅 Morning CFO Briefing — {d['company_name']} | {d['runway_months']:.1f}mo runway"
    if email:
        tasks.append(_send_email(email, subject, _format_email_html(d)))
    if phone:
        tasks.append(_send_sms(phone, _format_sms(d)))
    if slack_webhook:
        tasks.append(_send_slack(slack_webhook, _format_slack(d)))
    if not tasks:
        print("  ⚠  No delivery targets configured — printing briefing:\n")
        print(_format_sms(d))
    else:
        await asyncio.gather(*tasks)


async def main() -> None:
    parser = argparse.ArgumentParser(description="Send morning CFO briefings")
    parser.add_argument("--run-id",       required=True,  help="Run UUID from the dashboard")
    parser.add_argument("--company-name", default="Your Company")
    parser.add_argument("--email",        default=None,   help="Recipient email address")
    parser.add_argument("--phone",        default=None,   help="E.164 phone number for SMS")
    parser.add_argument("--slack",        default=os.getenv("SLACK_WEBHOOK_URL"), help="Slack webhook URL")
    args = parser.parse_args()

    print(f"→ Sending morning briefing for run {args.run_id}…")
    await send_briefing(
        run_id=args.run_id,
        company_name=args.company_name,
        email=args.email,
        phone=args.phone,
        slack_webhook=args.slack,
    )
    print("✅ Done.")


if __name__ == "__main__":
    asyncio.run(main())
