from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, Numeric, String, Text, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON


class Base(DeclarativeBase):
    pass


class RawFinancial(Base):
    """Raw transaction rows ingested from CSV or PDF uploads."""

    __tablename__ = "raw_financials"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    source_file: Mapped[str | None] = mapped_column(String(255), nullable=True)
    customer_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class KPISnapshot(Base):
    """Weekly KPI snapshot computed from raw financials."""

    __tablename__ = "kpi_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    mrr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    arr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    churn_rate: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    burn_rate: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    gross_margin: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    cac: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    ltv: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    wow_delta: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    mom_delta: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Anomaly(Base):
    """Anomaly record detected by IsolationForest or Chronos."""

    __tablename__ = "anomalies"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    metric: Mapped[str] = mapped_column(String(100), nullable=False)
    actual_value: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    expected_range: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class MarketSignal(Base):
    """Competitor market signal collected from Tavily or DuckDuckGo."""

    __tablename__ = "market_signals"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    competitor_name: Mapped[str] = mapped_column(String(255), nullable=False)
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    raw_source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Report(Base):
    """Board-ready CFO briefing generated by InsightWriterAgent."""

    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    executive_summary: Mapped[str] = mapped_column(Text, nullable=False)
    full_text: Mapped[str] = mapped_column(Text, nullable=False)
    distribution_status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending"
    )
    slack_message_ts: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Integration(Base):
    """OAuth token storage for Stripe and QuickBooks integrations."""

    __tablename__ = "integrations"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    platform: Mapped[str] = mapped_column(String(20), nullable=False)  # stripe | quickbooks
    access_token_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    refresh_token_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    realm_id: Mapped[str | None] = mapped_column(String(255), nullable=True)  # QuickBooks company ID
    company_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    last_sync_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class SyncLog(Base):
    """Audit log for integration sync operations."""

    __tablename__ = "sync_logs"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    integration_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False)  # success | error
    rows_synced: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CashBalance(Base):
    """Manual or synced current cash position for a run."""

    __tablename__ = "cash_balances"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    balance: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    as_of_date: Mapped[date] = mapped_column(Date, nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False, default="manual")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CommittedExpense(Base):
    """Recurring committed outflows (rent, payroll, SaaS subscriptions)."""

    __tablename__ = "committed_expenses"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    frequency: Mapped[str] = mapped_column(String(20), nullable=False)  # weekly|monthly|quarterly|annual
    next_payment_date: Mapped[date] = mapped_column(Date, nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False, default="other")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CashFlowForecast(Base):
    """13-week rolling cash flow forecast output (P10/P50/P90 bands)."""

    __tablename__ = "cash_flow_forecasts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_offset: Mapped[int] = mapped_column(Integer, nullable=False)  # 1–13
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    predicted_balance_p10: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    predicted_balance_p50: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    predicted_balance_p90: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    expected_inflows: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    expected_outflows: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class Contract(Base):
    """Annual or multi-year SaaS contracts for deferred revenue tracking."""

    __tablename__ = "contracts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    customer_id: Mapped[str] = mapped_column(String(255), nullable=False)
    total_value: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    start_date: Mapped[date] = mapped_column(Date, nullable=False)
    end_date: Mapped[date] = mapped_column(Date, nullable=False)
    payment_terms: Mapped[str] = mapped_column(String(50), nullable=False, default="annual")
    payment_received_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class DeferredRevenueSchedule(Base):
    """Monthly GAAP revenue recognition schedule per contract."""

    __tablename__ = "deferred_revenue_schedules"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    contract_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("contracts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    month_start: Mapped[date] = mapped_column(Date, nullable=False)
    recognized_revenue: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    deferred_balance: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)


class BoardDeck(Base):
    """Generated PowerPoint board deck files."""

    __tablename__ = "board_decks"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="generating")
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class FraudAlert(Base):
    """Suspicious transaction patterns detected by rule-based fraud analysis."""

    __tablename__ = "fraud_alerts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    pattern: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class CustomerProfile(Base):
    """Per-customer revenue metrics computed from raw financial rows."""

    __tablename__ = "customer_profiles"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    customer_id: Mapped[str] = mapped_column(String(255), nullable=False)
    total_revenue: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    weeks_active: Mapped[int] = mapped_column(Integer, nullable=False)
    avg_weekly_revenue: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False)
    first_seen: Mapped[date] = mapped_column(Date, nullable=False)
    last_seen: Mapped[date] = mapped_column(Date, nullable=False)
    churn_flag: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    segment: Mapped[str] = mapped_column(String(20), nullable=False)
    revenue_pct: Mapped[Decimal] = mapped_column(Numeric(8, 4), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AgentObservation(Base):
    """Periodic financial state snapshot observed by the autonomous CFO agent."""

    __tablename__ = "agent_observations"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    observed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    runway_months: Mapped[float] = mapped_column(Numeric(8, 2), nullable=False, default=0.0)
    burn_rate: Mapped[float] = mapped_column(Numeric(18, 2), nullable=False, default=0.0)
    mrr: Mapped[float] = mapped_column(Numeric(18, 2), nullable=False, default=0.0)
    burn_change_pct: Mapped[float] = mapped_column(Numeric(8, 2), nullable=False, default=0.0)
    mrr_change_pct: Mapped[float] = mapped_column(Numeric(8, 2), nullable=False, default=0.0)
    active_anomalies_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    fraud_alerts_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    raw_snapshot: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AgentPlan(Base):
    """Multi-step action plan created by the agent for a detected financial event."""

    __tablename__ = "agent_plans"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    observation_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("agent_observations.id", ondelete="CASCADE"), nullable=False
    )
    goal: Mapped[str] = mapped_column(Text, nullable=False)
    plan_type: Mapped[str] = mapped_column(String(50), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    decision_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class AgentAction(Base):
    """Individual action executed (or pending approval) as part of an agent plan."""

    __tablename__ = "agent_actions"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    plan_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("agent_plans.id", ondelete="CASCADE"), nullable=False, index=True
    )
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    action_type: Mapped[str] = mapped_column(String(50), nullable=False)
    params: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="executed")
    requires_approval: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    approval_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    result: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


__all__ = [
    "Base",
    "RawFinancial",
    "KPISnapshot",
    "Anomaly",
    "MarketSignal",
    "Report",
    "Integration",
    "SyncLog",
    "CashBalance",
    "CommittedExpense",
    "CashFlowForecast",
    "Contract",
    "DeferredRevenueSchedule",
    "BoardDeck",
    "FraudAlert",
    "CustomerProfile",
    "AgentObservation",
    "AgentPlan",
    "AgentAction",
]
