from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import Date, DateTime, Numeric, String, Text, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import JSON


class Base(DeclarativeBase):
    pass


class RawFinancial(Base):
    """Raw transaction rows ingested from CSV or PDF uploads."""

    __tablename__ = "raw_financials"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    source_file: Mapped[str | None] = mapped_column(String(255), nullable=True)
    customer_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class KPISnapshot(Base):
    """Weekly KPI snapshot computed from raw financials."""

    __tablename__ = "kpi_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    mrr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    arr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    churn_rate: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    burn_rate: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    gross_margin: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    cac: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    ltv: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    wow_delta: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    mom_delta: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Anomaly(Base):
    """Anomaly record detected by IsolationForest or Chronos."""

    __tablename__ = "anomalies"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    metric: Mapped[str] = mapped_column(String(100), nullable=False)
    actual_value: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    expected_range: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class MarketSignal(Base):
    """Competitor market signal collected from Tavily or DuckDuckGo."""

    __tablename__ = "market_signals"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    competitor_name: Mapped[str] = mapped_column(String(255), nullable=False)
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    raw_source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Report(Base):
    """Board-ready CFO briefing generated by InsightWriterAgent."""

    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    run_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    executive_summary: Mapped[str] = mapped_column(Text, nullable=False)
    full_text: Mapped[str] = mapped_column(Text, nullable=False)
    distribution_status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending"
    )
    slack_message_ts: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email_sent_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


__all__ = ["Base", "RawFinancial", "KPISnapshot", "Anomaly", "MarketSignal", "Report"]
